name: serbia_air_quality_monitor
description: "A Flutter application to monitor air quality in Serbia."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  provider: ^6.1.5+1
  path: ^1.9.1
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/datasets/shabac.csv
